# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoteWithPouchDb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NoteWithPouchDb

  target 'NoteWithPouchDb-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoteWithPouchDbTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
